# Generated by Django 4.1.6 on 2023-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
