# Generated by Django 4.1.6 on 2023-02-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0004_donation_post_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='post_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
