# Generated by Django 4.1.6 on 2023-02-09 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0003_rename_is_ordered_donation_is_booked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookeddonation',
            name='donation',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('food_details', models.TextField(blank=True, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('donar_contact', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agent.bookeddonation')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donar.donation')),
            ],
        ),
    ]
