# Generated by Django 4.1.6 on 2023-02-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_bookeddonation_donation_order_bookeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donar_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
