# Generated by Django 4.1.6 on 2023-02-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_order_donar_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booked_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
