# Generated by Django 4.1.6 on 2023-02-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_order_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
